# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.17)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget RW::gtest RW::gtest_main)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target RW::gtest
add_library(RW::gtest STATIC IMPORTED)

set_target_properties(RW::gtest PROPERTIES
  INTERFACE_COMPILE_OPTIONS "-DGTEST_HAS_PTHREAD=1"
  INTERFACE_INCLUDE_DIRECTORIES "/usr/src/gtest/include;/usr/src/gtest"
)

# Create imported target RW::gtest_main
add_library(RW::gtest_main STATIC IMPORTED)

set_target_properties(RW::gtest_main PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/src/gtest/include;/usr/src/gtest"
)

# Import target "RW::gtest" for configuration "Debug"
set_property(TARGET RW::gtest APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::gtest PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "Threads::Threads"
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libgtestd.a"
  )

# Import target "RW::gtest_main" for configuration "Debug"
set_property(TARGET RW::gtest_main APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::gtest_main PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "Threads::Threads;RW::gtest"
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libgtest_maind.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.17)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget RW::gtest RW::gtest_main)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target RW::gtest
add_library(RW::gtest STATIC IMPORTED)

set_target_properties(RW::gtest PROPERTIES
  INTERFACE_COMPILE_OPTIONS "-DGTEST_HAS_PTHREAD=1"
  INTERFACE_INCLUDE_DIRECTORIES "/usr/src/gtest/include;/usr/src/gtest"
)

# Create imported target RW::gtest_main
add_library(RW::gtest_main STATIC IMPORTED)

set_target_properties(RW::gtest_main PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/src/gtest/include;/usr/src/gtest"
)

# Import target "RW::gtest" for configuration "Debug"
set_property(TARGET RW::gtest APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::gtest PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "Threads::Threads"
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libgtestd.a"
  )

# Import target "RW::gtest_main" for configuration "Debug"
set_property(TARGET RW::gtest_main APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::gtest_main PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "Threads::Threads;RW::gtest"
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libgtest_maind.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.17)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget RW::gtest RW::gtest_main)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target RW::gtest
add_library(RW::gtest STATIC IMPORTED)

set_target_properties(RW::gtest PROPERTIES
  INTERFACE_COMPILE_OPTIONS "-DGTEST_HAS_PTHREAD=1"
  INTERFACE_INCLUDE_DIRECTORIES "/usr/src/gtest/include;/usr/src/gtest"
)

# Create imported target RW::gtest_main
add_library(RW::gtest_main STATIC IMPORTED)

set_target_properties(RW::gtest_main PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/src/gtest/include;/usr/src/gtest"
)

# Import target "RW::gtest" for configuration "Debug"
set_property(TARGET RW::gtest APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::gtest PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "Threads::Threads"
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libgtestd.a"
  )

# Import target "RW::gtest_main" for configuration "Debug"
set_property(TARGET RW::gtest_main APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::gtest_main PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "Threads::Threads;RW::gtest"
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libgtest_maind.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
