# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.17)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget RW::pqp RW::yaobi RW::sdurw_csgjs RW::sdurw_core RW::sdurw_plugin RW::sdurw_common RW::sdurw_math RW::sdurw_kinematics RW::sdurw_geometry RW::sdurw_sensor RW::sdurw_graspplanning RW::sdurw_models RW::sdurw_trajectory RW::sdurw_proximity RW::sdurw_graphics RW::sdurw_invkin RW::sdurw_pathplanning RW::sdurw_loaders RW::sdurw RW::sdurw_algorithms RW::sdurw_task RW::sdurw_assembly RW::sdurw_calibration RW::sdurw_control RW::sdurw_opengl RW::sdurw_proximitystrategies RW::sdurw_pathoptimization RW::sdurw_pathplanners RW::sdurw_simulation RW::sdurw_csg RW::sdurw_analytic_geometry RW::sdurw_simplefinger)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target RW::pqp
add_library(RW::pqp STATIC IMPORTED)

set_target_properties(RW::pqp PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWork/ext/rwpqp"
)

# Create imported target RW::yaobi
add_library(RW::yaobi STATIC IMPORTED)

set_target_properties(RW::yaobi PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWork/ext/rwyaobi/include"
)

# Create imported target RW::sdurw_csgjs
add_library(RW::sdurw_csgjs STATIC IMPORTED)

set_target_properties(RW::sdurw_csgjs PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWork/ext/csgjs/src"
)

# Create imported target RW::sdurw_core
add_library(RW::sdurw_core SHARED IMPORTED)

set_target_properties(RW::sdurw_core PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include;/home/zw/CLionProjects/RobWork/RobWork/src"
  INTERFACE_LINK_LIBRARIES "Boost::filesystem;Boost::serialization;Boost::system;Boost::thread;Boost::program_options;Boost::date_time;Boost::headers"
)

# Create imported target RW::sdurw_plugin
add_library(RW::sdurw_plugin SHARED IMPORTED)

set_target_properties(RW::sdurw_plugin PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include;/home/zw/CLionProjects/RobWork/RobWork/src"
  INTERFACE_LINK_LIBRARIES "Boost::filesystem;Boost::serialization;Boost::system;Boost::thread;Boost::program_options;Boost::date_time;Boost::headers;dl;RW::sdurw_core"
)

# Create imported target RW::sdurw_common
add_library(RW::sdurw_common SHARED IMPORTED)

set_target_properties(RW::sdurw_common PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/eigen3;/home/zw/CLionProjects/RobWork/RobWork/src"
  INTERFACE_LINK_LIBRARIES "Boost::filesystem;Boost::serialization;Boost::system;Boost::thread;Boost::program_options;Boost::date_time;Boost::headers;RW::sdurw_core"
)

# Create imported target RW::sdurw_math
add_library(RW::sdurw_math SHARED IMPORTED)

set_target_properties(RW::sdurw_math PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/eigen3;/home/zw/CLionProjects/RobWork/RobWork/src"
  INTERFACE_LINK_LIBRARIES "RW::sdurw_core;RW::sdurw_common;/usr/lib/gcc/x86_64-linux-gnu/9/libgomp.so;/usr/lib/x86_64-linux-gnu/libpthread.so"
)

# Create imported target RW::sdurw_kinematics
add_library(RW::sdurw_kinematics SHARED IMPORTED)

set_target_properties(RW::sdurw_kinematics PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWork/src"
  INTERFACE_LINK_LIBRARIES "RW::sdurw_core;RW::sdurw_common;RW::sdurw_math"
)

# Create imported target RW::sdurw_geometry
add_library(RW::sdurw_geometry SHARED IMPORTED)

set_target_properties(RW::sdurw_geometry PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include;/home/zw/CLionProjects/RobWork/RobWork/ext/rwpqp;/home/zw/CLionProjects/RobWork/RobWork/src;/usr/include/eigen3"
  INTERFACE_LINK_LIBRARIES "Boost::filesystem;Boost::serialization;Boost::system;Boost::thread;Boost::program_options;Boost::date_time;Boost::headers;RW::sdurw_core;RW::sdurw_common;RW::sdurw_math;RW::sdurw_kinematics"
)

# Create imported target RW::sdurw_sensor
add_library(RW::sdurw_sensor SHARED IMPORTED)

set_target_properties(RW::sdurw_sensor PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWork/src"
  INTERFACE_LINK_LIBRARIES "Boost::filesystem;Boost::serialization;Boost::system;Boost::thread;Boost::program_options;Boost::date_time;Boost::headers;RW::sdurw_core;RW::sdurw_common;RW::sdurw_math;RW::sdurw_geometry;RW::sdurw_kinematics"
)

# Create imported target RW::sdurw_graspplanning
add_library(RW::sdurw_graspplanning SHARED IMPORTED)

set_target_properties(RW::sdurw_graspplanning PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWork/src"
  INTERFACE_LINK_LIBRARIES "RW::sdurw_core;RW::sdurw_common;RW::sdurw_math;RW::sdurw_geometry;RW::sdurw_sensor"
)

# Create imported target RW::sdurw_models
add_library(RW::sdurw_models SHARED IMPORTED)

set_target_properties(RW::sdurw_models PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include;/home/zw/CLionProjects/RobWork/RobWork/src"
  INTERFACE_LINK_LIBRARIES "Boost::filesystem;Boost::serialization;Boost::system;Boost::thread;Boost::program_options;Boost::date_time;Boost::headers;RW::sdurw_core;RW::sdurw_common;RW::sdurw_kinematics;RW::sdurw_math;RW::sdurw_geometry;RW::sdurw_sensor"
)

# Create imported target RW::sdurw_trajectory
add_library(RW::sdurw_trajectory SHARED IMPORTED)

set_target_properties(RW::sdurw_trajectory PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/eigen3;/usr/include;/home/zw/CLionProjects/RobWork/RobWork/src"
  INTERFACE_LINK_LIBRARIES "RW::sdurw_core;RW::sdurw_math;RW::sdurw_models"
)

# Create imported target RW::sdurw_proximity
add_library(RW::sdurw_proximity SHARED IMPORTED)

set_target_properties(RW::sdurw_proximity PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include;/home/zw/CLionProjects/RobWork/RobWork/src"
  INTERFACE_LINK_LIBRARIES "Boost::filesystem;Boost::serialization;Boost::system;Boost::thread;Boost::program_options;Boost::date_time;Boost::headers;RW::sdurw_core;RW::sdurw_common;RW::sdurw_math;RW::sdurw_geometry;RW::sdurw_models;RW::sdurw_kinematics"
)

# Create imported target RW::sdurw_graphics
add_library(RW::sdurw_graphics SHARED IMPORTED)

set_target_properties(RW::sdurw_graphics PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include;/home/zw/CLionProjects/RobWork/RobWork/src"
  INTERFACE_LINK_LIBRARIES "Boost::filesystem;Boost::serialization;Boost::system;Boost::thread;Boost::program_options;Boost::date_time;Boost::headers;RW::sdurw_core;RW::sdurw_math;RW::sdurw_kinematics;RW::sdurw_geometry;RW::sdurw_sensor;RW::sdurw_models"
)

# Create imported target RW::sdurw_invkin
add_library(RW::sdurw_invkin SHARED IMPORTED)

set_target_properties(RW::sdurw_invkin PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include;/home/zw/CLionProjects/RobWork/RobWork/src"
  INTERFACE_LINK_LIBRARIES "Boost::filesystem;Boost::serialization;Boost::system;Boost::thread;Boost::program_options;Boost::date_time;Boost::headers;RW::sdurw_core;RW::sdurw_math;RW::sdurw_kinematics;RW::sdurw_models;RW::sdurw_trajectory;RW::sdurw_proximity"
)

# Create imported target RW::sdurw_pathplanning
add_library(RW::sdurw_pathplanning SHARED IMPORTED)

set_target_properties(RW::sdurw_pathplanning PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include;/home/zw/CLionProjects/RobWork/RobWork/src"
  INTERFACE_LINK_LIBRARIES "Boost::filesystem;Boost::serialization;Boost::system;Boost::thread;Boost::program_options;Boost::date_time;Boost::headers;RW::sdurw_core;RW::sdurw_math;RW::sdurw_kinematics;RW::sdurw_proximity;RW::sdurw_models;RW::sdurw_trajectory;RW::sdurw_invkin"
)

# Create imported target RW::sdurw_loaders
add_library(RW::sdurw_loaders SHARED IMPORTED)

set_target_properties(RW::sdurw_loaders PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include;/usr/include;/home/zw/CLionProjects/RobWork/RobWork/src"
  INTERFACE_LINK_LIBRARIES "Boost::filesystem;Boost::serialization;Boost::system;Boost::thread;Boost::program_options;Boost::date_time;Boost::headers;RW::sdurw_core;RW::sdurw_common;RW::sdurw_math;RW::sdurw_kinematics;RW::sdurw_geometry;RW::sdurw_sensor;RW::sdurw_models;RW::sdurw_proximity;RW::sdurw_graphics;RW::sdurw_trajectory;/usr/lib/x86_64-linux-gnu/libxerces-c.so"
)

# Create imported target RW::sdurw
add_library(RW::sdurw INTERFACE IMPORTED)

set_target_properties(RW::sdurw PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWork/src"
  INTERFACE_LINK_LIBRARIES "RW::sdurw_core;RW::sdurw_common;RW::sdurw_math;RW::sdurw_kinematics;RW::sdurw_plugin;RW::sdurw_geometry;RW::sdurw_sensor;RW::sdurw_models;RW::sdurw_proximity;RW::sdurw_graphics;RW::sdurw_trajectory;RW::sdurw_invkin;RW::sdurw_pathplanning;RW::sdurw_graspplanning;RW::sdurw_loaders"
)

# Create imported target RW::sdurw_algorithms
add_library(RW::sdurw_algorithms SHARED IMPORTED)

set_target_properties(RW::sdurw_algorithms PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWork/src"
  INTERFACE_LINK_LIBRARIES "RW::sdurw"
)

# Create imported target RW::sdurw_task
add_library(RW::sdurw_task SHARED IMPORTED)

set_target_properties(RW::sdurw_task PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWork/src"
  INTERFACE_LINK_LIBRARIES "RW::sdurw"
)

# Create imported target RW::sdurw_assembly
add_library(RW::sdurw_assembly SHARED IMPORTED)

set_target_properties(RW::sdurw_assembly PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWork/src"
  INTERFACE_LINK_LIBRARIES "RW::sdurw"
)

# Create imported target RW::sdurw_calibration
add_library(RW::sdurw_calibration SHARED IMPORTED)

set_target_properties(RW::sdurw_calibration PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWork/src"
  INTERFACE_LINK_LIBRARIES "RW::sdurw"
)

# Create imported target RW::sdurw_control
add_library(RW::sdurw_control SHARED IMPORTED)

set_target_properties(RW::sdurw_control PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWork/src"
  INTERFACE_LINK_LIBRARIES "RW::sdurw;RW::sdurw_core;RW::sdurw_math;RW::sdurw_models"
)

# Create imported target RW::sdurw_opengl
add_library(RW::sdurw_opengl SHARED IMPORTED)

set_target_properties(RW::sdurw_opengl PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWork/src"
  INTERFACE_LINK_LIBRARIES "RW::sdurw;RW::sdurw_core;RW::sdurw_sensor;RW::sdurw_models;/usr/lib/x86_64-linux-gnu/libOpenGL.so;/usr/lib/x86_64-linux-gnu/libGLX.so;/usr/lib/x86_64-linux-gnu/libGLU.so"
)

# Create imported target RW::sdurw_proximitystrategies
add_library(RW::sdurw_proximitystrategies SHARED IMPORTED)

set_target_properties(RW::sdurw_proximitystrategies PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWork/src"
  INTERFACE_LINK_LIBRARIES "RW::sdurw_core;RW::sdurw_common;RW::sdurw_math;RW::sdurw_geometry;RW::sdurw_proximity;RW::sdurw_kinematics;RW::sdurw;RW::pqp"
)

# Create imported target RW::sdurw_pathoptimization
add_library(RW::sdurw_pathoptimization SHARED IMPORTED)

set_target_properties(RW::sdurw_pathoptimization PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWork/src"
  INTERFACE_LINK_LIBRARIES "RW::sdurw"
)

# Create imported target RW::sdurw_pathplanners
add_library(RW::sdurw_pathplanners SHARED IMPORTED)

set_target_properties(RW::sdurw_pathplanners PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWork/src"
  INTERFACE_LINK_LIBRARIES "RW::sdurw_core;RW::sdurw_common;RW::sdurw_math;RW::sdurw_kinematics;RW::sdurw_models;RW::sdurw_trajectory;RW::sdurw_algorithms;RW::sdurw"
)

# Create imported target RW::sdurw_simulation
add_library(RW::sdurw_simulation SHARED IMPORTED)

set_target_properties(RW::sdurw_simulation PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWork/src"
  INTERFACE_LINK_LIBRARIES "RW::sdurw;RW::sdurw_control;RW::sdurw_core;RW::sdurw_common;RW::sdurw_kinematics;RW::sdurw_geometry;RW::sdurw_sensor;RW::sdurw_models"
)

# Create imported target RW::sdurw_csg
add_library(RW::sdurw_csg SHARED IMPORTED)

set_target_properties(RW::sdurw_csg PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWork/src"
  INTERFACE_LINK_LIBRARIES "RW::sdurw;RW::sdurw_csgjs"
)

# Create imported target RW::sdurw_analytic_geometry
add_library(RW::sdurw_analytic_geometry SHARED IMPORTED)

set_target_properties(RW::sdurw_analytic_geometry PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWork/src"
  INTERFACE_LINK_LIBRARIES "RW::sdurw"
)

# Create imported target RW::sdurw_simplefinger
add_library(RW::sdurw_simplefinger SHARED IMPORTED)

set_target_properties(RW::sdurw_simplefinger PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWork/src"
  INTERFACE_LINK_LIBRARIES "RW::sdurw"
)

# Import target "RW::pqp" for configuration "Debug"
set_property(TARGET RW::pqp APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::pqp PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libpqp.a"
  )

# Import target "RW::yaobi" for configuration "Debug"
set_property(TARGET RW::yaobi APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::yaobi PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libyaobi.a"
  )

# Import target "RW::sdurw_csgjs" for configuration "Debug"
set_property(TARGET RW::sdurw_csgjs APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::sdurw_csgjs PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libsdurw_csgjs.a"
  )

# Import target "RW::sdurw_core" for configuration "Debug"
set_property(TARGET RW::sdurw_core APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::sdurw_core PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libsdurw_core.so"
  IMPORTED_SONAME_DEBUG "libsdurw_core.so"
  )

# Import target "RW::sdurw_plugin" for configuration "Debug"
set_property(TARGET RW::sdurw_plugin APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::sdurw_plugin PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libsdurw_plugin.so"
  IMPORTED_SONAME_DEBUG "libsdurw_plugin.so"
  )

# Import target "RW::sdurw_common" for configuration "Debug"
set_property(TARGET RW::sdurw_common APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::sdurw_common PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libsdurw_common.so"
  IMPORTED_SONAME_DEBUG "libsdurw_common.so"
  )

# Import target "RW::sdurw_math" for configuration "Debug"
set_property(TARGET RW::sdurw_math APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::sdurw_math PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libsdurw_math.so"
  IMPORTED_SONAME_DEBUG "libsdurw_math.so"
  )

# Import target "RW::sdurw_kinematics" for configuration "Debug"
set_property(TARGET RW::sdurw_kinematics APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::sdurw_kinematics PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libsdurw_kinematics.so"
  IMPORTED_SONAME_DEBUG "libsdurw_kinematics.so"
  )

# Import target "RW::sdurw_geometry" for configuration "Debug"
set_property(TARGET RW::sdurw_geometry APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::sdurw_geometry PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libsdurw_geometry.so"
  IMPORTED_SONAME_DEBUG "libsdurw_geometry.so"
  )

# Import target "RW::sdurw_sensor" for configuration "Debug"
set_property(TARGET RW::sdurw_sensor APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::sdurw_sensor PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libsdurw_sensor.so"
  IMPORTED_SONAME_DEBUG "libsdurw_sensor.so"
  )

# Import target "RW::sdurw_graspplanning" for configuration "Debug"
set_property(TARGET RW::sdurw_graspplanning APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::sdurw_graspplanning PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libsdurw_graspplanning.so"
  IMPORTED_SONAME_DEBUG "libsdurw_graspplanning.so"
  )

# Import target "RW::sdurw_models" for configuration "Debug"
set_property(TARGET RW::sdurw_models APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::sdurw_models PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libsdurw_models.so"
  IMPORTED_SONAME_DEBUG "libsdurw_models.so"
  )

# Import target "RW::sdurw_trajectory" for configuration "Debug"
set_property(TARGET RW::sdurw_trajectory APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::sdurw_trajectory PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libsdurw_trajectory.so"
  IMPORTED_SONAME_DEBUG "libsdurw_trajectory.so"
  )

# Import target "RW::sdurw_proximity" for configuration "Debug"
set_property(TARGET RW::sdurw_proximity APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::sdurw_proximity PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libsdurw_proximity.so"
  IMPORTED_SONAME_DEBUG "libsdurw_proximity.so"
  )

# Import target "RW::sdurw_graphics" for configuration "Debug"
set_property(TARGET RW::sdurw_graphics APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::sdurw_graphics PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libsdurw_graphics.so"
  IMPORTED_SONAME_DEBUG "libsdurw_graphics.so"
  )

# Import target "RW::sdurw_invkin" for configuration "Debug"
set_property(TARGET RW::sdurw_invkin APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::sdurw_invkin PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libsdurw_invkin.so"
  IMPORTED_SONAME_DEBUG "libsdurw_invkin.so"
  )

# Import target "RW::sdurw_pathplanning" for configuration "Debug"
set_property(TARGET RW::sdurw_pathplanning APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::sdurw_pathplanning PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libsdurw_pathplanning.so"
  IMPORTED_SONAME_DEBUG "libsdurw_pathplanning.so"
  )

# Import target "RW::sdurw_loaders" for configuration "Debug"
set_property(TARGET RW::sdurw_loaders APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::sdurw_loaders PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libsdurw_loaders.so"
  IMPORTED_SONAME_DEBUG "libsdurw_loaders.so"
  )

# Import target "RW::sdurw_algorithms" for configuration "Debug"
set_property(TARGET RW::sdurw_algorithms APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::sdurw_algorithms PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libsdurw_algorithms.so"
  IMPORTED_SONAME_DEBUG "libsdurw_algorithms.so"
  )

# Import target "RW::sdurw_task" for configuration "Debug"
set_property(TARGET RW::sdurw_task APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::sdurw_task PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libsdurw_task.so"
  IMPORTED_SONAME_DEBUG "libsdurw_task.so"
  )

# Import target "RW::sdurw_assembly" for configuration "Debug"
set_property(TARGET RW::sdurw_assembly APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::sdurw_assembly PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_DEBUG "RW::sdurw_task"
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libsdurw_assembly.so"
  IMPORTED_SONAME_DEBUG "libsdurw_assembly.so"
  )

# Import target "RW::sdurw_calibration" for configuration "Debug"
set_property(TARGET RW::sdurw_calibration APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::sdurw_calibration PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libsdurw_calibration.so"
  IMPORTED_SONAME_DEBUG "libsdurw_calibration.so"
  )

# Import target "RW::sdurw_control" for configuration "Debug"
set_property(TARGET RW::sdurw_control APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::sdurw_control PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libsdurw_control.so"
  IMPORTED_SONAME_DEBUG "libsdurw_control.so"
  )

# Import target "RW::sdurw_opengl" for configuration "Debug"
set_property(TARGET RW::sdurw_opengl APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::sdurw_opengl PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libsdurw_opengl.so"
  IMPORTED_SONAME_DEBUG "libsdurw_opengl.so"
  )

# Import target "RW::sdurw_proximitystrategies" for configuration "Debug"
set_property(TARGET RW::sdurw_proximitystrategies APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::sdurw_proximitystrategies PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libsdurw_proximitystrategies.so"
  IMPORTED_SONAME_DEBUG "libsdurw_proximitystrategies.so"
  )

# Import target "RW::sdurw_pathoptimization" for configuration "Debug"
set_property(TARGET RW::sdurw_pathoptimization APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::sdurw_pathoptimization PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_DEBUG "RW::sdurw_proximitystrategies"
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libsdurw_pathoptimization.so"
  IMPORTED_SONAME_DEBUG "libsdurw_pathoptimization.so"
  )

# Import target "RW::sdurw_pathplanners" for configuration "Debug"
set_property(TARGET RW::sdurw_pathplanners APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::sdurw_pathplanners PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libsdurw_pathplanners.so"
  IMPORTED_SONAME_DEBUG "libsdurw_pathplanners.so"
  )

# Import target "RW::sdurw_simulation" for configuration "Debug"
set_property(TARGET RW::sdurw_simulation APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::sdurw_simulation PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libsdurw_simulation.so"
  IMPORTED_SONAME_DEBUG "libsdurw_simulation.so"
  )

# Import target "RW::sdurw_csg" for configuration "Debug"
set_property(TARGET RW::sdurw_csg APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::sdurw_csg PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libsdurw_csg.so"
  IMPORTED_SONAME_DEBUG "libsdurw_csg.so"
  )

# Import target "RW::sdurw_analytic_geometry" for configuration "Debug"
set_property(TARGET RW::sdurw_analytic_geometry APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::sdurw_analytic_geometry PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libsdurw_analytic_geometry.so"
  IMPORTED_SONAME_DEBUG "libsdurw_analytic_geometry.so"
  )

# Import target "RW::sdurw_simplefinger" for configuration "Debug"
set_property(TARGET RW::sdurw_simplefinger APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RW::sdurw_simplefinger PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_DEBUG "RW::sdurw_csg"
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork/libs/debug/libsdurw_simplefinger.so"
  IMPORTED_SONAME_DEBUG "libsdurw_simplefinger.so"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
