
// 
// This is an autogenerated header file. Do not edit this. If you need
// to change the definitions then change them in RobWorkConfig.hpp.in  
// 

#define RWS_VERSION "22.2.3-main"
#define RWS_VERSION_MAJOR 22 
#define RWS_VERSION_MINOR 2
#define RWS_VERSION_PATCH 3
#define RWS_COMPILE_PLUGIN_DIR "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWorkStudio/libs/debug/plugins" // This define is only used to find plugins on the system compiling robwork

#define RWS_REVISION "3617b72"

#define RWS_HAVE_GLUT 1
/* #undef RWS_HAVE_LUA */
/* #undef RWS_USE_STATIC_LINK_PLUGINS */
#define RWS_USE_QT5 1
#define RWS_USE_PYTHON3 1
/* #undef RWS_USE_PYTHON2 */
#define RWS_USE_PYTHON 1
