# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.17)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget RWS::qtpropertybrowser RWS::QCodeEditor RWS::sdurws RWS::sdurws_atask RWS::sdurws_gtask RWS::sdurws_jog RWS::sdurws_log RWS::sdurws_playback RWS::sdurws_propertyview RWS::sdurws_treeview RWS::sdurws_planning RWS::sdurws_sensors RWS::sdurws_workcelleditor RWS::sdurws_workcelleditorplugin RWS::sdurws_robworkstudioapp)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target RWS::qtpropertybrowser
add_library(RWS::qtpropertybrowser STATIC IMPORTED)

set_target_properties(RWS::qtpropertybrowser PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWorkStudio/ext/qtpropertybrowser/src"
  INTERFACE_LINK_LIBRARIES "Qt5::Core;Qt5::Gui;Qt5::Widgets;Qt5::OpenGL"
)

# Create imported target RWS::QCodeEditor
add_library(RWS::QCodeEditor STATIC IMPORTED)

set_target_properties(RWS::QCodeEditor PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWorkStudio/ext/QCodeEditor/include"
  INTERFACE_LINK_LIBRARIES "Qt5::Core;Qt5::Widgets;Qt5::Gui"
)

# Create imported target RWS::sdurws
add_library(RWS::sdurws SHARED IMPORTED)

set_target_properties(RWS::sdurws PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWorkStudio/src"
  INTERFACE_LINK_LIBRARIES "RWS::qtpropertybrowser;/usr/lib/x86_64-linux-gnu/libpython3.8.so;Qt5::Core;Qt5::Gui;Qt5::Widgets;Qt5::OpenGL;RW::sdurw_proximitystrategies;RW::sdurw_opengl;RW::sdurw;/usr/lib/x86_64-linux-gnu/libOpenGL.so;/usr/lib/x86_64-linux-gnu/libGLX.so;/usr/lib/x86_64-linux-gnu/libGLU.so"
)

# Create imported target RWS::sdurws_atask
add_library(RWS::sdurws_atask MODULE IMPORTED)

set_target_properties(RWS::sdurws_atask PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWorkStudio/src/rwslibs/atask;/home/zw/CLionProjects/RobWork/RobWorkStudio/src"
  INTERFACE_LINK_LIBRARIES "RWS::sdurws;Qt5::Core;Qt5::Gui;Qt5::Widgets;Qt5::OpenGL"
)

# Create imported target RWS::sdurws_gtask
add_library(RWS::sdurws_gtask MODULE IMPORTED)

set_target_properties(RWS::sdurws_gtask PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWorkStudio/src/rwslibs/gtask;/home/zw/CLionProjects/RobWork/RobWorkStudio/src"
  INTERFACE_LINK_LIBRARIES "RWS::sdurws;Qt5::Core;Qt5::Gui;Qt5::Widgets;Qt5::OpenGL"
)

# Create imported target RWS::sdurws_jog
add_library(RWS::sdurws_jog MODULE IMPORTED)

set_target_properties(RWS::sdurws_jog PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWorkStudio/src"
  INTERFACE_LINK_LIBRARIES "RWS::sdurws;Qt5::Core;Qt5::Gui;Qt5::Widgets;Qt5::OpenGL;RW::sdurw"
)

# Create imported target RWS::sdurws_log
add_library(RWS::sdurws_log MODULE IMPORTED)

set_target_properties(RWS::sdurws_log PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWorkStudio/src"
  INTERFACE_LINK_LIBRARIES "RWS::sdurws;Qt5::Core;Qt5::Gui;Qt5::Widgets;Qt5::OpenGL"
)

# Create imported target RWS::sdurws_playback
add_library(RWS::sdurws_playback MODULE IMPORTED)

set_target_properties(RWS::sdurws_playback PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWorkStudio/src"
  INTERFACE_LINK_LIBRARIES "RWS::sdurws;Qt5::Core;Qt5::Gui;Qt5::Widgets;Qt5::OpenGL;RW::sdurw"
)

# Create imported target RWS::sdurws_propertyview
add_library(RWS::sdurws_propertyview MODULE IMPORTED)

set_target_properties(RWS::sdurws_propertyview PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWorkStudio/src"
  INTERFACE_LINK_LIBRARIES "RWS::sdurws;Qt5::Core;Qt5::Gui;Qt5::Widgets;Qt5::OpenGL"
)

# Create imported target RWS::sdurws_treeview
add_library(RWS::sdurws_treeview MODULE IMPORTED)

set_target_properties(RWS::sdurws_treeview PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWorkStudio/src"
  INTERFACE_LINK_LIBRARIES "RWS::sdurws;Qt5::Core;Qt5::Gui;Qt5::Widgets;Qt5::OpenGL;RW::sdurw"
)

# Create imported target RWS::sdurws_planning
add_library(RWS::sdurws_planning MODULE IMPORTED)

set_target_properties(RWS::sdurws_planning PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWorkStudio/src"
  INTERFACE_LINK_LIBRARIES "RWS::sdurws;Qt5::Core;Qt5::Gui;Qt5::Widgets;Qt5::OpenGL;RW::sdurw"
)

# Create imported target RWS::sdurws_sensors
add_library(RWS::sdurws_sensors MODULE IMPORTED)

set_target_properties(RWS::sdurws_sensors PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWorkStudio/src"
  INTERFACE_LINK_LIBRARIES "RWS::sdurws;Qt5::Core;Qt5::Gui;Qt5::Widgets;Qt5::OpenGL;RW::sdurw"
)

# Create imported target RWS::sdurws_workcelleditor
add_library(RWS::sdurws_workcelleditor SHARED IMPORTED)

set_target_properties(RWS::sdurws_workcelleditor PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWorkStudio/src"
  INTERFACE_LINK_LIBRARIES "RWS::sdurws;Qt5::Core;Qt5::Gui;Qt5::Widgets;Qt5::OpenGL;RW::sdurw"
)

# Create imported target RWS::sdurws_workcelleditorplugin
add_library(RWS::sdurws_workcelleditorplugin MODULE IMPORTED)

set_target_properties(RWS::sdurws_workcelleditorplugin PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWorkStudio/src"
  INTERFACE_LINK_LIBRARIES "RWS::sdurws;RWS::sdurws_workcelleditor"
)

# Create imported target RWS::sdurws_robworkstudioapp
add_library(RWS::sdurws_robworkstudioapp SHARED IMPORTED)

set_target_properties(RWS::sdurws_robworkstudioapp PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/zw/CLionProjects/RobWork/RobWorkStudio/src"
  INTERFACE_LINK_LIBRARIES "RWS::sdurws;Qt5::Core;Qt5::Gui;Qt5::Widgets;Qt5::OpenGL"
)

# Import target "RWS::qtpropertybrowser" for configuration "Debug"
set_property(TARGET RWS::qtpropertybrowser APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RWS::qtpropertybrowser PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWorkStudio/libs/debug/libqtpropertybrowser.a"
  )

# Import target "RWS::QCodeEditor" for configuration "Debug"
set_property(TARGET RWS::QCodeEditor APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RWS::QCodeEditor PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWorkStudio/libs/debug/libQCodeEditor.a"
  )

# Import target "RWS::sdurws" for configuration "Debug"
set_property(TARGET RWS::sdurws APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RWS::sdurws PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWorkStudio/libs/debug/libsdurws.so"
  IMPORTED_SONAME_DEBUG "libsdurws.so"
  )

# Import target "RWS::sdurws_atask" for configuration "Debug"
set_property(TARGET RWS::sdurws_atask APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RWS::sdurws_atask PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_DEBUG ""
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWorkStudio/libs/debug/plugins/libsdurws_atask.so"
  IMPORTED_NO_SONAME_DEBUG "TRUE"
  )

# Import target "RWS::sdurws_gtask" for configuration "Debug"
set_property(TARGET RWS::sdurws_gtask APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RWS::sdurws_gtask PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_DEBUG ""
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWorkStudio/libs/debug/plugins/libsdurws_gtask.so"
  IMPORTED_NO_SONAME_DEBUG "TRUE"
  )

# Import target "RWS::sdurws_jog" for configuration "Debug"
set_property(TARGET RWS::sdurws_jog APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RWS::sdurws_jog PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_DEBUG ""
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWorkStudio/libs/debug/plugins/libsdurws_jog.so"
  IMPORTED_NO_SONAME_DEBUG "TRUE"
  )

# Import target "RWS::sdurws_log" for configuration "Debug"
set_property(TARGET RWS::sdurws_log APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RWS::sdurws_log PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_DEBUG ""
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWorkStudio/libs/debug/plugins/libsdurws_log.so"
  IMPORTED_NO_SONAME_DEBUG "TRUE"
  )

# Import target "RWS::sdurws_playback" for configuration "Debug"
set_property(TARGET RWS::sdurws_playback APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RWS::sdurws_playback PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_DEBUG ""
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWorkStudio/libs/debug/plugins/libsdurws_playback.so"
  IMPORTED_NO_SONAME_DEBUG "TRUE"
  )

# Import target "RWS::sdurws_propertyview" for configuration "Debug"
set_property(TARGET RWS::sdurws_propertyview APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RWS::sdurws_propertyview PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_DEBUG ""
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWorkStudio/libs/debug/plugins/libsdurws_propertyview.so"
  IMPORTED_NO_SONAME_DEBUG "TRUE"
  )

# Import target "RWS::sdurws_treeview" for configuration "Debug"
set_property(TARGET RWS::sdurws_treeview APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RWS::sdurws_treeview PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_DEBUG ""
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWorkStudio/libs/debug/plugins/libsdurws_treeview.so"
  IMPORTED_NO_SONAME_DEBUG "TRUE"
  )

# Import target "RWS::sdurws_planning" for configuration "Debug"
set_property(TARGET RWS::sdurws_planning APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RWS::sdurws_planning PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_DEBUG ""
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWorkStudio/libs/debug/plugins/libsdurws_planning.so"
  IMPORTED_NO_SONAME_DEBUG "TRUE"
  )

# Import target "RWS::sdurws_sensors" for configuration "Debug"
set_property(TARGET RWS::sdurws_sensors APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RWS::sdurws_sensors PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_DEBUG ""
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWorkStudio/libs/debug/plugins/libsdurws_sensors.so"
  IMPORTED_NO_SONAME_DEBUG "TRUE"
  )

# Import target "RWS::sdurws_workcelleditor" for configuration "Debug"
set_property(TARGET RWS::sdurws_workcelleditor APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RWS::sdurws_workcelleditor PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWorkStudio/libs/debug/libsdurws_workcelleditor.so"
  IMPORTED_SONAME_DEBUG "libsdurws_workcelleditor.so"
  )

# Import target "RWS::sdurws_workcelleditorplugin" for configuration "Debug"
set_property(TARGET RWS::sdurws_workcelleditorplugin APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RWS::sdurws_workcelleditorplugin PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_DEBUG ""
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWorkStudio/libs/debug/plugins/libsdurws_workcelleditorplugin.so"
  IMPORTED_NO_SONAME_DEBUG "TRUE"
  )

# Import target "RWS::sdurws_robworkstudioapp" for configuration "Debug"
set_property(TARGET RWS::sdurws_robworkstudioapp APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RWS::sdurws_robworkstudioapp PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWorkStudio/libs/debug/libsdurws_robworkstudioapp.so"
  IMPORTED_SONAME_DEBUG "libsdurws_robworkstudioapp.so"
  )

# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "RW::sdurw_proximitystrategies" "RW::sdurw_opengl" "RW::sdurw" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
