// 
// This is an autogenerated header file. Do not edit this. If you need
// to change the definitions then change them in RobWorkConfig.hpp.in  
// 

#define RW_VERSION "22.2.3-main"
#define RW_VERSION_MAJOR 22 
#define RW_VERSION_MINOR 2
#define RW_VERSION_PATCH 3

#define RW_REVISION "3617b72"
#define RW_BUILD_TYPE "debug"

#define RW_BUILD_DIR "/home/zw/CLionProjects/RobWork/cmake-build-debug/RobWork"

#ifdef _WIN32
    #define SLASH '\\'
#else
    #define SLASH '/'
#endif

#define RW_HAVE_PQP 1
#define RW_HAVE_YAOBI 1
#define RW_HAVE_FCL 1
/* #undef RW_HAVE_BULLET */
/* #undef RW_HAVE_EIGEN */
#define RW_HAVE_ASSIMP 1
/* #undef RW_HAVE_ZLIB */
/* #undef RW_HAVE_MINIZIP */
/* #undef RW_BUILD_CALIBRATION */
/* #undef RW_HAVE_MATHEMATICA */
#define RW_HAVE_XERCES 1
#define RW_HAVE_OMP 1
#define RW_HAVE_GLUT 1

